---
- name: Install EPEL
  package:
    name: epel-release
    state: installed

- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Copy Nginx configuration
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Start Nginx
  service:
    name: nginx
    state: started
